- name: Install php-fpm & php extensions
  become: true
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
  - php-fpm
  - php-gd
  - php-curl
  - php-mysql
  - php-dom
  - php-xml
  - php-zip
  - php-mbstring
  - php-odbc
  - php-mcrypt

- name: Configure php-fpm with apache2
  become: true
  copy: src=files/www.conf dest=/etc/php/7.0/fpm/pool.d/

- name: Copy fcgi-php-fpm conf file
  become: true
  copy: src=files/fcgi-php-fpm.conf dest=/etc/apache2/conf-available/fcgi-php-fpm.conf

- name: Enable fcgi-php-fpm apache config file
  become: yes
  command: a2enconf fcgi-php-fpm

- name: Restart php-fpm
  become: yes
  service: name=php7.0-fpm state=restarted

- name: Restart apache
  become: yes
  service: name=apache2 state=restarted