---


- name: check for previous mysql installation
  shell: "[ -f /usr/sbin/mysqld ]"
  ignore_errors: True
  register: mysql_server_installed

- name: copy preseed file
  template:
    src: mysql_seed.j2
    dest: /root/mysql.seed
  when: mysql_server_installed|failed


- name: pressed mysql config
  command: /usr/bin/debconf-set-selections /root/mysql.seed
  when: mysql_server_installed|failed

- name: pressed mysql config
  command: /usr/bin/debconf-set-selections /root/mysql.seed
  when: mysql_server_installed|failed

- name: remove mysql seed file
  file:
    path: /root/mysql.seed
    state: absent

- name: Install mysql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libmysqlclient-dev


- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes