---
- name: Install mysql
  apt:
    name: "{{ item }}"
    state: present
  with_items:    
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libmysqlclient-dev


- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: configure root mysql credentials
  copy:
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644
    content: |
      [client]
      user=root
      password={{ mysql_root_password }}

- name: configure root mysql credentials
  copy:
    dest: /home/ubuntu/.my.cnf
    owner: ubuntu
    group: ubuntu
    mode: 0644
    content: |
      [client]
      user=root
      password={{ mysql_root_password }}
