---
- name: Install mysql
  apt:
    name: "{{ item }}"
    state: present
  with_items:    
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libmysqlclient-dev


- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: Update MySQL root password for all root accounts
  mysql_user: name=root 
              host={{ item }} 
              password={{ mysql_root_password }}
              login_user=root
              login_password=""
              state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost